### ISSUE TITLE
AppSettings missing

### ISSUE THREAD

**Issue by yeahia2508** [yunusefendi52/quran_app#1]
Below AppSettings dart file missing

```
if (_encrypter == null) {
        try {
          String key = AppSettings.key;
          String iv = AppSettings.iv;
          _encrypter = Encrypter(
            Salsa20(
              key,
              iv,
            ),
          );
        } catch (error) {
          print(error?.toString());
        }
      }
```

**Comment by yunusefendi52** [comment]
The key and iv property is meant to decrypt the url in [database.db](https://github.com/yunusefendi52/quran_app/blob/master/assets/quran-data/translations.db) which to prevent abuse. I think I added it to .gitignore. For the workaround you can add the AppSettings with `key` and `iv` property or change the code like below:
```
String key = '';
String iv = '';
```

I am still looking the best way to expose the AppSettings without showing the real key
Let me know if that is working for you.

**Comment by yeahia2508** [comment]
Form where I can collect this key and iv?

**Comment by yunusefendi52** [comment]
Unfortunately, key and iv is the key to decrypt the link to the translation and I don't want the link to be abused

**Comment by yunusefendi52** [comment]
Closing this, please reopen if you still have this issue
