### ISSUE TITLE
Contact Information

### ISSUE THREAD

**Issue by yunusemrecetin** [yunusefendi52/quran_app#10]
Hi @yunusefendi52 ,

I want to develop many features for this project. Can you open a Slack Channel or Telegram etc.? Btw If you contact me maybe we can talk about features.

**Comment by yunusefendi52** [comment]
HI,
For know maybe you can create issue in the github explain the feature so we can discuss it more.

I haven't really check out about Slack/Telegram channel, but that is really a great idea to create one!

**Comment by yunusefendi52** [comment]
I just realize your name is also Yunus 😂

**Comment by yunusemrecetin** [comment]
We have the same name :) I opened a Telegram channel for this repo, you can join from [this](https://t.me/flutterquran) link, and we can talk about this repo.
