### ISSUE TITLE
moor ffi deprecated

### ISSUE THREAD

**Issue by mikealphakilo** [yunusefendi52/quran_app#12]
plz update the project the door dependencies are deprecated 

[quran_app-master] flutter pub get
Running "flutter pub get" in quran_app-master...                 2,648ms
Invalid plugin specification moor_ffi.

**Comment by mikealphakilo** [comment]
Invalid plugin specification moor_ffi. plz look into it.I cant use the app

**Comment by mikealphakilo** [comment]
plz update the dependencies

**Comment by yunusefendi52** [comment]
Still working on it, but will be updated the app to Flutter v2.x see https://github.com/yunusefendi52/quran_app/tree/flutter-v2

**Comment by yunusefendi52** [comment]
Merged to master branch
