### ISSUE TITLE
Want to remove indonesian langauge and want to add Nepali translation

### ISSUE THREAD

**Issue by Alidhuniya** [yunusefendi52/quran_app#2]
Jumping verse is not working? 

Hi bro, from Nepal. I want to add Nepali translation instead of Indonesian language which is similar to Hindi but meaning gives different. New to flutter. What steps do you suggest? I find hard to understand and DB file is not opening.

**Comment by yunusefendi52** [comment]
Jumping verse currently not working, waiting [this flutter issue](https://github.com/flutter/flutter/issues/12319)

I couldn't find the Nepal translation, do you know the source? if you do maybe I can add Nepal translation

**Comment by Alidhuniya** [comment]
> Jumping verse currently not working, waiting [this flutter issue](https://github.com/flutter/flutter/issues/12319)
> 
> I couldn't find the Nepal translation, do you know the source? if you do maybe I can add Nepal translation

**Comment by Alidhuniya** [comment]
> Jumping verse currently not working, waiting [this flutter issue](https://github.com/flutter/flutter/issues/12319)
> 
> I couldn't find the Nepal translation, do you know the source? if you do maybe I can add Nepal translation

I have pdf document,from there you can add each verse. here is my fb profile link: https://www.facebook.com/dhuniya.1920    .DM me directly I will send you
