### ISSUE TITLE
Can Bookmark be a shortcut

### ISSUE THREAD

**Issue by zukinaru** [yunusefendi52/quran_app#3]
Hi,

i test making a bookmark, but it seems cant be clicked to go to specific surah and verse...

is it possible or not yet implemented ?

thanks

**Comment by yunusefendi52** [comment]
I haven't implemented the feature, waiting for this issue [https://github.com/flutter/flutter/issues/12319](https://github.com/flutter/flutter/issues/12319)

**Comment by zukinaru** [comment]
Have you tried below solutions :

https://gist.github.com/wtoalabi/51a045ea6a541a7d6ba2aaca6db3dfad
or
https://gist.github.com/wtoalabi/51a045ea6a541a7d6ba2aaca6db3dfad

if yes and still not work, please let me know....

thank you

**Comment by zukinaru** [comment]
@yunusefendi52 

Have you tried below solutions :

https://gist.github.com/wtoalabi/51a045ea6a541a7d6ba2aaca6db3dfad
or
https://github.com/quire-io/scroll-to-index

if yes and still not work, please let me know....

thank you

**Comment by yunusefendi52** [comment]
Hi, I use [https://github.com/google/flutter.widgets/tree/master/lib/src/scrollable_positioned_list](https://github.com/google/flutter.widgets/tree/master/lib/src/scrollable_positioned_list), you check out the implementation in [refactor](https://github.com/yunusefendi52/quran_app/tree/refactor) branch
