### ISSUE TITLE
Translations from Tanzil

### ISSUE THREAD

**Issue by muhammadarslan** [yunusefendi52/quran_app#5]
I have checked the translations at tanzil, they are not in db format and the data sequance and tables are not in same format as well, did you download the translations and make you own format? waiting for your reply.

**Comment by bedifferent2** [comment]
Hi brother,
Did you fix the jumpTo aya and bookmark problem?

**Comment by muhammadarslan** [comment]
I mean did you make db format file for sqllite yourself? or you have downloaded these db files from somewhere?

**Comment by bedifferent2** [comment]
I think he did because I tried to add from tanzil and I searched in google I didn't find anything.

But I asked you about the bookmark and jumpTo aya did you fix the problem?

**Comment by muhammadarslan** [comment]
Jump to aya does not work and i have not tried to fix my self yet, but i have also found the problem in quran text in some places it's not correct

**Comment by bedifferent2** [comment]
Yes I seen that and I try to fix the txt I will send you a new quran db when I finish inshallah

**Comment by yunusefendi52** [comment]
Hi guys, I am working on refactoring this repo [refactor](https://github.com/yunusefendi52/quran_app/tree/refactor), on that branch I also add the function to jump to specific aya

I'll keep this issue open until I finish refactoring this repo

**Comment by yunusefendi52** [comment]
Refactoring done! please checkoout/pull master branch
