### ISSUE TITLE
flutter_localizations version confilct

### ISSUE THREAD

**Issue by ismailelmogy** [yunusefendi52/quran_app#7]
can you run the app on the latest version of flutter ... I faced this error : 
 quran_app depends on intl ^0.15.7, version solving failed.
pub get failed (1; So, because quran_app depends on intl ^0.15.7, version solving failed.)
exit code 1

**Comment by yunusefendi52** [comment]
Yah I faced that error too, you can try changing the intl version to 0.16.0
