### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by murtraja** [yunusefendi52/quran_app#9]
Afzal us Salaam,
Wanted to know the license in which you have open sourced the project so that the code can be reused in another project.

**Comment by yunusefendi52** [comment]
I'll check about the license in the weekend

**Comment by aqeelshamz** [comment]
Assalamu alaikum,

Please checkout my Flutter package: https://pub.dev/packages/quran
It may be useful.

**Comment by rafimemmeni** [comment]
Thanks

**Comment by yunusefendi52** [comment]
License added in master branch
